version: '3.4'

services:
  db:
    image: 279063/udemy-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile    
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: restAspNet
    ports:
      - "3308:3306"
    networks:
      - udemy-network

  webapi-persons:
    image: 279063/webapi-persons
    build:
      context: .
      dockerfile: WebApi-Persons/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network

networks: 
    udemy-network:
        driver: bridge